Bright-Burn/ConstaConstructor

src/components/FormConstructor/FormConstructorFormBlockConfigure/DroppableLayer/DroppableLayer.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TabsFormElement/TabsFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TabsFormElement/index.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TabsFormElement/types.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ConpomonentStructure/ComponentItems/ComponentItems.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/Settings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TabsSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TabsSettings/TabsSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TabsSettings/types.ts, src/components/FormConstructor/store/formElements/tabsTypes.ts, src/components/FormConstructor/store/formElements/types.ts
=> Добавлен компонент Tabs

src/components/FormConstructor/FormConstructorFormBlockConfigure/DroppableLayer/FormGroupDict.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ProjectGrid/Icons.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ProjectGrid/ProjectGrid.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ProjectGrid/index.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ProjectGrid/mocks.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ProjectGrid/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ProjectGrid/types.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ConponentsStructure/BaseComponents/BaseComponents.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/SelectableLayer/SelectableLayerFitSpace.tsx, src/components/FormConstructor/store/formElements/types.ts
=> Cетка проектов

.gitattributes
Добавить настройку для окончания строки LF для shell скриптов при коммите
=> feat: Добавить настройку git eol LF для *.sh

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardLayout/ComponentCardLayout.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BaseSettings/MarginService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BaseSettings/PaddingService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx, src/components/FormConstructor/store/formElements/layoutTypes.ts
Добавил возможность отключать отступы, добавить дефолтное значение для layout-items
=> fix: Добавить возможность отключать отступы

src/components/FormConstructor/FormConstructorFormBlockConfigure/DroppableLayer/DroppableLayer.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ExpertiseForm/ExpertiseForm.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentTree/ComponentTree.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentTree/Tree/index.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentTree/utils.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/FormBlock/FormBlock.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/FormBlock/Pages/Pages.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/FormBlock/Pages/types.ts, src/components/FormConstructor/projectSaveLoad/saveProject.ts, src/components/FormConstructor/projectSaveLoad/types.ts, src/components/FormConstructor/store/formElements/BreadcrumbsTypes.ts, src/components/FormConstructor/store/formElements/index.ts, src/components/FormConstructor/store/formElements/initialState.ts, src/components/FormConstructor/store/formElements/reducers/addNewPage.ts, src/components/FormConstructor/store/formElements/reducers/changeActivePage.ts, src/components/FormConstructor/store/formElements/reducers/deletePage.ts, src/components/FormConstructor/store/formElements/reducers/loadProjectFromJson.ts, src/components/FormConstructor/store/formElements/slices.ts, src/components/FormConstructor/store/formElements/types.ts, src/components/FormConstructor/utils/getElementsOnLayer.ts, src/components/FormConstructor/utils/getNewGroupParentLevel.ts, src/components/FormConstructor/utils/index.ts
Добавить фильтрацию дерева по выбранной странице, отображение выбранной страницы. Создание Layout при создании новой страницы.
=> Добавить фильтрацию дерева по выбранной странице, отображение выбранной странице 

src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ButtonFormElement/ButtonFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TextFieldFormElement/TextFieldFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TextFieldFormElement/types.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ButtonSettings/ButtonSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ButtonSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ButtonSettings/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/FilledSettings/FilledSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/FilledSettings/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/Settings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/SelectableLayer/SelectableLayer.tsx, src/components/FormConstructor/coreTypes/buttonTypes.ts, src/components/FormConstructor/coreTypes/index.ts, src/components/FormConstructor/coreTypes/textFieldTypes.ts, src/components/FormConstructor/coreTypes/types.ts
=> refactor: Обновить стилизацию настроек кнопки

src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TabsFormElement/TabsFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TabsSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TabsSettings/TabsSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TabsSettings/styles.module.css, src/components/FormConstructor/coreTypes/tabsTypes.ts
=> Обновить стилизацию настроек табов

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/InformerSettings/InformerConstants.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/InformerSettings/InformerSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/InformerSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/InformerSettings/styles.module.css
=> Обновить стилизацию настроек информера

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/CardSettings/CardSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/CardSettings/styles.module.css
=> Обновить дизайн настроек карточки

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/IconSettings/IconSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/IconSettings/IconsConstants.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/IconSettings/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SettingsPanelQualifier.tsx
Я так понимаю вместо color надо использовать view
=> Обновить стилизацию настроек иконки

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SwitchSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SwitchSettings/SwitchSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SwitchSettings/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SwitchSettings/types.ts, src/components/FormConstructor/coreTypes/SwitchTypes.ts
=> Обновить стиль настроек переключателя

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/RadioButtonSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/RadioButtonSettings/RadioButtonSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/RadioButtonSettings/styles.module.css
=> Обновить дизайн настроек радиокнопки

src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/TagFormElement/TagFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TagSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TagSettings/TagSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TagSettings/styles.module.css
=> Обновить дизайн настроек тэга

src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/DateTimeFormElement/DateTimeFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardDataTime/ComponentCardDataTime.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/DataTimeSettings/DataTimeSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/DataTimeSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/DataTimeSettings/styles.module.css, src/components/FormConstructor/coreTypes/dataTimeTypes.ts
=> Обновить дизайн настроек datetime

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/CheckboxSettings/CheckboxSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/CheckboxSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/CheckboxSettings/styles.module.css, src/components/FormConstructor/coreTypes/checkboxTypes.ts
=> Обновить дизайн настоек чекбокса

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/BreadcrumbsConstants.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/BreadcrumbsSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BreadcrumbsSettings/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ButtonSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ChoiceGroupSettings/ChoiceGroupSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/IconSettings/IconSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/IconSettings/IconsConstants.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TagSettings/ItemsService.ts, src/components/FormConstructor/coreTypes/BreadcrumbsTypes.ts, src/components/FormConstructor/coreTypes/buttonTypes.ts, src/components/FormConstructor/coreTypes/iconTypes.ts, src/components/FormConstructor/coreTypes/index.ts, src/components/FormConstructor/coreTypes/tagTypes.ts
=> Обновить дизайн настроек хлебных крошек

src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/ComboBoxFormElement/ComboBoxFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardComboBox/ComponentCardComboBox.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ComboBoxSettings/ComboBoxSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ComboBoxSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ComboBoxSettings/fileTypes.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ComboBoxSettings/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ComboBoxSettings/types.ts, src/components/FormConstructor/coreTypes/comboBoxTypes.ts, src/components/FormConstructor/coreTypes/index.ts
=> Обновить дизайн настроек комбобокса

src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/SelectFormElement/SelectFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardSelect/ComponentCardSelect.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SelectSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SelectSettings/SelectSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SelectSettings/fileTypes.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SelectSettings/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/SelectSettings/types.ts, src/components/FormConstructor/coreTypes/selectTypes.ts
=> Обновить дизайн для настроек селекта

src/components/FormConstructor/FormConstructorFormBlockConfigure/Elements/Badge/BadgeFormElement.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BadgeSettings/BadgeSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BadgeSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/BadgeSettings/styles.module.css, src/components/FormConstructor/coreTypes/badgeTypes.ts, src/components/FormConstructor/coreTypes/index.ts
иконку справа поставить нельзя, убрали из консты такой вариант
=> fix: Обновить стиль настроек у badge

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentGrid/ComponentGrid.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentGrid/ComponentsGrid.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentGrid/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardLayout/ComponentCardLayout.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardLayout/styles.module.css, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/types.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/content.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentsStructure.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/content.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/types.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TabsSettings/TabsSettings.tsx
=> Обновить дизайн сетки

src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/ButtonSettings/ButtonSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/FilledSettings/FilledSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextFieldSettings/ItemsService.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextFieldSettings/TextFieldSettings.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/TextFieldSettings/styles.module.css, src/components/FormConstructor/coreTypes/index.ts
=> Обновить дизайн настроек для текстфилда

src/components/ConstaPalette/ConstaPalette.tsx, src/components/ConstaPalette/styles.module.css, src/components/ConstaPalette/types.ts, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/ComponentsStructure/ComponentItems/ComponentCard/ComponentCardLayout/ComponentCardLayout.tsx, src/components/FormConstructor/FormConstructorFormBlockConfigure/Panels/Settings/LayoutSettings/LayoutSettings.tsx
=> Добавлен плейсхолдер для bgc у layout
